# @name CreateLeafNode
## TEST-EXPECT-STATUS: [200,201]
POST {{ApiBaseUrl}}/api/nodes
Content-Type: application/json

{
  "name": "Leaf Node",
  "code": "LEAF-{{$guid}}",
  "type": 4
}

###

# @name GetLeafTree
## TEST-EXPECT-STATUS: [200]
GET {{ApiBaseUrl}}/api/nodes/{{CreateLeafNode.response.body.$.data.id}}/tree
