# @name CreateLeafNode
## TEST-EXPECT-STATUS: [200,201]
POST {{ApiBaseUrl}}/api/nodes
Content-Type: application/json

{
  "name": "Temporary Department",
  "code": "TMP-{{$guid}}",
  "type": 4
}

###

# @name DeleteNode
## TEST-EXPECT-STATUS: [200]
DELETE {{ApiBaseUrl}}/api/nodes/{{CreateLeafNode.response.body.$.data.id}}