# @name CreateRoot
## TEST-EXPECT-STATUS: [200,201]
POST {{ApiBaseUrl}}/api/nodes
Content-Type: application/json

{
  "name": "Project A",
  "code": "DIV-{{$guid}}",
  "type": 3
}


###

# @name CreateChild
## TEST-EXPECT-STATUS: [200,201]
POST {{ApiBaseUrl}}/api/nodes
Content-Type: application/json

{
  "name": "Department A",
  "code": "DEP-{{$guid}}",
  "type": 4,
  "parentId": "{{CreateRoot.response.body.$.data.id}}"
}

###

# @name GetDeleted
## TEST-EXPECT-STATUS: [200]
GET {{ApiBaseUrl}}/api/nodes/by-type?types=Department